// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EqDrbTh63_euZrTyOnrdxIS9TSWNzMc',
    appId: '1:149392077239:web:9c1535d6d7cf7e244cf832',
    messagingSenderId: '149392077239',
    projectId: 'fir-webview-7f4ff',
    authDomain: 'fir-webview-7f4ff.firebaseapp.com',
    storageBucket: 'fir-webview-7f4ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBellbczL9fAyxRrtr2kdhSbpJlog0QeYM',
    appId: '1:149392077239:android:9aa72349a67e96834cf832',
    messagingSenderId: '149392077239',
    projectId: 'fir-webview-7f4ff',
    storageBucket: 'fir-webview-7f4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjntiw6Hlu_JJFsdXh56KTCQfkynF-hI',
    appId: '1:149392077239:ios:23c489915c5abefe4cf832',
    messagingSenderId: '149392077239',
    projectId: 'fir-webview-7f4ff',
    storageBucket: 'fir-webview-7f4ff.firebasestorage.app',
    iosBundleId: 'com.example.demoWebview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjntiw6Hlu_JJFsdXh56KTCQfkynF-hI',
    appId: '1:149392077239:ios:23c489915c5abefe4cf832',
    messagingSenderId: '149392077239',
    projectId: 'fir-webview-7f4ff',
    storageBucket: 'fir-webview-7f4ff.firebasestorage.app',
    iosBundleId: 'com.example.demoWebview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EqDrbTh63_euZrTyOnrdxIS9TSWNzMc',
    appId: '1:149392077239:web:8f1a2be28ea091604cf832',
    messagingSenderId: '149392077239',
    projectId: 'fir-webview-7f4ff',
    authDomain: 'fir-webview-7f4ff.firebaseapp.com',
    storageBucket: 'fir-webview-7f4ff.firebasestorage.app',
  );
}
